version: '3.8'

services:
  auth-service:
    build: ./microservices/auth-service
    ports:
      - '3005:3005'
    env_file:
      - .env
    volumes:
      - ../../database.db:/app/microservices/auth-service/../../database.db

  post-service:
    build: ./microservices/post-service
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - ../../database.db:/app/microservices/post-service/../../database.db

  rating-service:
    build: ./microservices/rating-service
    ports:
      - '3002:3002'
    env_file:
      - .env
    volumes:
      - ../../database.db:/app/microservices/rating-service/../../database.db

  comment-service:
    build: ./microservices/comment-service
    ports:
      - '3003:3003'
    env_file:
      - .env
    volumes:
      - ../../database.db:/app/microservices/comment-service/../../database.db

  admin-service:
    build: ./microservices/admin-service
    ports:
      - '3004:3004'
    env_file:
      - .env
    volumes:
      - ../../database.db:/app/microservices/admin-service/../../database.db

  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    env_file:
      - .env
